<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>

</body>
<script>
  /** 
   * Promise 
   * 对象是一个代理对象（代理一个值），
   * 被代理的值在Promise对象创建时可能是未知的。
   * 它允许你为异步操作的成功和失败分别绑定相应的处理方法（handlers）。
   *  这让异步方法可以像同步方法那样返回值，
   * 但并不是立即返回最终执行结果，
   * 而是一个能代表未来出现的结果的promise对象
   * 
   * // 参数
   * executor { Function }
   * executor 带有两个参数 resolve reject ，这两个参数均为函数
   * // 属性
   * status {String} 'pending' | 'fulfilled' | 'rejcted'
   * // 方法
   * then
   * catch
   * all
   * race
   * reject
   * resolve
   */

  // promise 3种状态
  const PENDING = 'pending'
  const FULFILLED = 'fulfilled'
  const REJECTED = 'rejcted'

  function MyPromise(executor) {

    this.status = PENDING // 状态
    this.result = null // 结果
    this.queueFulFilled = [] // 成功执行队列
    this.queueRejected = [] // 失败执行队列
    try {
      executor(resolve.bind(this), reject.bind(this))
    } catch (e) {
      reject.bind(this)
    }


    // resolve 执行
    function resolve(value) {
      console.log('value: ', value)
      if (this.status === PENDING) {
        const res = value
        console.log('res: ', res);
        this.status = FULFILLED
        this.result = res
      }
    }
    // reject 执行
    function reject(value) {
      console.log('value: ', value);
      if (this.status === PENDING) {
        const res = value
        this.status = REJECTED
        this.result = res
      }
    }
  }
  MyPromise.prototype = {
    // 中间件 下一步
    next() {
      let fn = this.queue.shift()
      fn && fn()
    },
    then() {
      if()
      return this
    },
    catch () {
      return this
    }
  }


  const myPromise = new MyPromise((resolve, reject) => {
    const num = Math.floor(Math.random() * 10)
    console.log('num: ', num);
    if (num >= 5) {
      resolve(num)
    } else {
      reject(num)
    }
  }).then((res) => {
    console.log('res: ', res);
  }).catch(err => {
    console.log('err: ', err);
  })
</script>

</html>